apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-platformnavigator-assetrepo
spec:
  destination:
    namespace: gitops-cp-platformnavigator
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/gitops-cp-platformnavigator/assetrepo
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-cp-asset-repository-ocp4
    targetRevision: main
    helm:
      releaseName: assetrepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
