apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-platformnavigator-ibm-entitlement-key
spec:
  destination:
    namespace: gitops-cp-platformnavigator
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: >-
      payload/1-infrastructure/namespace/gitops-cp-platformnavigator/ibm-entitlement-key
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-cp-asset-repository-ocp4
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
